# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CommWithServer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Article_pb2 as Article__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x43ommWithServer.proto\x1a\rArticle.proto\"J\n\x11JoinServerRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x19\n\x07\x61\x64\x64ress\x18\x03 \x01(\x0b\x32\x08.Address\"\"\n\x12LeaveServerRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"K\n\x12GetArticlesRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\'\n\x0f\x41rticleResquest\x18\x02 \x01(\x0b\x32\x0e.ArticleFormat\"G\n\x16PublishArticlesRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x1f\n\x07\x61rticle\x18\x02 \x01(\x0b\x32\x0e.ArticleFormat\"$\n\x12JoinServerResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"%\n\x13LeaveServerResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"6\n\x13GetArticlesResponse\x12\x1f\n\x07\x61rticle\x18\x01 \x01(\x0b\x32\x0e.ArticleFormat\")\n\x17PublishArticlesResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\x8b\x02\n\x0e\x43ommWithServer\x12\x37\n\nJoinServer\x12\x12.JoinServerRequest\x1a\x13.JoinServerResponse\"\x00\x12:\n\x0bLeaveServer\x12\x13.LeaveServerRequest\x1a\x14.LeaveServerResponse\"\x00\x12<\n\x0bGetArticles\x12\x13.GetArticlesRequest\x1a\x14.GetArticlesResponse\"\x00\x30\x01\x12\x46\n\x0fPublishArticles\x12\x17.PublishArticlesRequest\x1a\x18.PublishArticlesResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CommWithServer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _JOINSERVERREQUEST._serialized_start=39
  _JOINSERVERREQUEST._serialized_end=113
  _LEAVESERVERREQUEST._serialized_start=115
  _LEAVESERVERREQUEST._serialized_end=149
  _GETARTICLESREQUEST._serialized_start=151
  _GETARTICLESREQUEST._serialized_end=226
  _PUBLISHARTICLESREQUEST._serialized_start=228
  _PUBLISHARTICLESREQUEST._serialized_end=299
  _JOINSERVERRESPONSE._serialized_start=301
  _JOINSERVERRESPONSE._serialized_end=337
  _LEAVESERVERRESPONSE._serialized_start=339
  _LEAVESERVERRESPONSE._serialized_end=376
  _GETARTICLESRESPONSE._serialized_start=378
  _GETARTICLESRESPONSE._serialized_end=432
  _PUBLISHARTICLESRESPONSE._serialized_start=434
  _PUBLISHARTICLESRESPONSE._serialized_end=475
  _COMMWITHSERVER._serialized_start=478
  _COMMWITHSERVER._serialized_end=745
# @@protoc_insertion_point(module_scope)
