# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CommWithRegistryServer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Article_pb2 as Article__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x43ommWithRegistryServer.proto\x1a\rArticle.proto\"F\n\x14GetServerListRequest\x12\x13\n\x04name\x18\x01 \x01(\x0b\x32\x05.Name\x12\x19\n\x07\x61\x64\x64ress\x18\x02 \x01(\x0b\x32\x08.Address\"G\n\x15GetServerListResponse\x12\x13\n\x04name\x18\x01 \x01(\x0b\x32\x05.Name\x12\x19\n\x07\x61\x64\x64ress\x18\x02 \x01(\x0b\x32\x08.Address\":\n\x0fRegisterRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x19\n\x07\x61\x64\x64ress\x18\x02 \x01(\x0b\x32\x08.Address\"\"\n\x10RegisterResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\x8f\x01\n\x16\x43ommWithRegistryServer\x12\x42\n\rGetServerList\x12\x15.GetServerListRequest\x1a\x16.GetServerListResponse\"\x00\x30\x01\x12\x31\n\x08Register\x12\x10.RegisterRequest\x1a\x11.RegisterResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CommWithRegistryServer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETSERVERLISTREQUEST._serialized_start=47
  _GETSERVERLISTREQUEST._serialized_end=117
  _GETSERVERLISTRESPONSE._serialized_start=119
  _GETSERVERLISTRESPONSE._serialized_end=190
  _REGISTERREQUEST._serialized_start=192
  _REGISTERREQUEST._serialized_end=250
  _REGISTERRESPONSE._serialized_start=252
  _REGISTERRESPONSE._serialized_end=286
  _COMMWITHREGISTRYSERVER._serialized_start=289
  _COMMWITHREGISTRYSERVER._serialized_end=432
# @@protoc_insertion_point(module_scope)
