# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Article.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rArticle.proto\x12\x0bgrpc_protos\x1a\x1fgoogle/protobuf/timestamp.proto\"\t\n\x07\x46\x61shion\"\n\n\x08Politics\"\x08\n\x06Sports\"\xdb\x01\n\x07\x41rticle\x12\'\n\x07\x66\x61shion\x18\x01 \x01(\x0b\x32\x14.grpc_protos.FashionH\x00\x12)\n\x08politics\x18\x02 \x01(\x0b\x32\x15.grpc_protos.PoliticsH\x00\x12%\n\x06sports\x18\x03 \x01(\x0b\x32\x13.grpc_protos.SportsH\x00\x12\x0e\n\x06\x61uthor\x18\x04 \x01(\t\x12,\n\x08time_rec\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07\x63ontent\x18\x06 \x01(\tB\x06\n\x04type\"\xd2\x01\n\x0f\x41rticleResponse\x12\'\n\x07\x66\x61shion\x18\x01 \x01(\x0b\x32\x14.grpc_protos.FashionH\x00\x12)\n\x08politics\x18\x02 \x01(\x0b\x32\x15.grpc_protos.PoliticsH\x00\x12%\n\x06sports\x18\x03 \x01(\x0b\x32\x13.grpc_protos.SportsH\x00\x12\x0e\n\x06\x61uthor\x18\x04 \x01(\t\x12,\n\x08time_rec\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x06\n\x04type\"6\n\x0e\x41rticleRequest\x12$\n\x06\x61uthor\x18\x01 \x01(\x0b\x32\x14.grpc_protos.Articleb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Article_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FASHION._serialized_start=63
  _FASHION._serialized_end=72
  _POLITICS._serialized_start=74
  _POLITICS._serialized_end=84
  _SPORTS._serialized_start=86
  _SPORTS._serialized_end=94
  _ARTICLE._serialized_start=97
  _ARTICLE._serialized_end=316
  _ARTICLERESPONSE._serialized_start=319
  _ARTICLERESPONSE._serialized_end=529
  _ARTICLEREQUEST._serialized_start=531
  _ARTICLEREQUEST._serialized_end=585
# @@protoc_insertion_point(module_scope)
