# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ClientToRegistryServer_pb2 as ClientToRegistryServer__pb2


class ClientToRegistryServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetServerList = channel.unary_stream(
                '/grpc_protos.ClientToRegistryServer/GetServerList',
                request_serializer=ClientToRegistryServer__pb2.GetServerListRequest.SerializeToString,
                response_deserializer=ClientToRegistryServer__pb2.GetServerListResponse.FromString,
                )


class ClientToRegistryServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetServerList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientToRegistryServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetServerList': grpc.unary_stream_rpc_method_handler(
                    servicer.GetServerList,
                    request_deserializer=ClientToRegistryServer__pb2.GetServerListRequest.FromString,
                    response_serializer=ClientToRegistryServer__pb2.GetServerListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc_protos.ClientToRegistryServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ClientToRegistryServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetServerList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/grpc_protos.ClientToRegistryServer/GetServerList',
            ClientToRegistryServer__pb2.GetServerListRequest.SerializeToString,
            ClientToRegistryServer__pb2.GetServerListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
